# Generated by Django 3.2.4 on 2021-06-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='vehicle',
            field=models.IntegerField(default=1),
        ),
    ]
