# Generated by Django 3.2.4 on 2021-06-14 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.JSONField()),
                ('x', models.IntegerField(max_length=10000)),
                ('y', models.IntegerField(max_length=10000)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.images')),
            ],
        ),
    ]
